### ISSUE TITLE
Identificação de conhecimento para os níveis

### ISSUE THREAD

**Issue by woliveiras** [woliveiras/front-end-career#1]
Quais os requisitos para cada nível profissional (junior, pleno, senior)?

**Comment by grodrigues** [comment]
Júnior

Html5
Css3
Javascript
Angular, Backbones ou Rect.js

**Comment by woliveiras** [comment]
No caso dos Frameworks, pensei em colocar que o Junior precisa conhecer algum, mas não especificar qual. Por que depende muito de região, demanda de empregos, mercado, etc, @grodrigues. 

Fora que o iniciante precisa mesmo aprender a linguagem e não esquentar muito com Frameworks se não ele se perde. kkkkk

Melhor colocar um frame como opcional, dependendo só da demanda local.

Que tal?

**Comment by grodrigues** [comment]
Verdade concordo. Mas aqui em Recife tem empresas que estão pedindo isso para estagiários mas linguagem sempre é mais importante.

**Comment by woliveiras** [comment]
Os níveis foram adicionados, qualquer problema podemos reabrir a issue ou tratar em outra. :smile:

**Comment by Marcelosilva10** [comment]
Júnior

Html
Css
Javascript
Jquery
Node.js
