### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by jonatasleon** [woliveiras/front-end-career#13]
Há possibilidade desse projeto virar uma página web? O conteúdo ficaria mais acessível a qualquer um, a quem tá começando, a quem já está na área. Navegar através da pastas no gh pode desmotivar algumas pessoas.

**Comment by woliveiras** [comment]
Creio que da sim @jonatasleon 

Só levantarmos um pessoal pra tacar lenha nessa ideia que da pra fazer 😄

**Comment by jonatasleon** [comment]
O que fiz no meu [repo pessoal](https://github.com/jonatasleon/jonatasleon.github.io) pode ser útil. 
Toda vez que faço push na branch dev, o Travis-CI executa o conteúdo de .travis, esse por sua vez roda o script deploy.sh, então todo processo de build mandado para a branch master. Tudo de forma automatizada. Não sou tão criativo quando se trata de Layout e Design, desde que outros cuidem dessa parte, posso me dispor a contribuir na criação do site

**Comment by woliveiras** [comment]
Booooooooa meu querido! Ai sim!

Tenho um esquema parecido [aqui](https://github.com/woliveiras/woliveiras.github.io/tree/development).
Bora agitar esse negócio cara! 

Vou criar um Gitter pra ficar mais fácil essa comunicação.

**Comment by ubirajarapelli** [comment]
Se quiser, nóis leiauta sabagaça!

**Comment by grodrigues** [comment]
Qual que coisa estamos ai sou Design e Front pelo menos quero implementar uma página.

**Comment by woliveiras** [comment]
Booooa cara!

Da para o @grodrigues e o @ubirajarapelli trabalharem em um Layout e eu e o @jonatasleon trabalharmos no código.

Que tal?

**Comment by woliveiras** [comment]
Da pra fazer usando Jekyll e sai coisa linda.

Ex.: https://woliveiras.com.br/my-precious-links/

**Comment by grodrigues** [comment]
Velho eu queria implementar no Jekyll para aprender, mas já que não deu Tranquilo. Estou na correria vou fazer o layout e mostro.

**Comment by woliveiras** [comment]
Da pra implementar no Jekyll sim homi. Por que achou que não deu mano @grodrigues?

kkkkkkk

**Comment by Marcelosilva10** [comment]
Tenho que enviar as traduções ainda. viu @woliveiras coloca o Bussu também com o Duolingo na parte de app em Inglês.

**Comment by woliveiras** [comment]
Opa, sem problemas @Marcelosilva10 

Pra mim também está bem corrido e não da tempo de priorizar os projetos. :cry:

**Comment by kvnol** [comment]
A página poderia ser simples, até, algo no estilo do Browser Diet do @zenorocha: https://browserdiet.com/pt/

**Comment by woliveiras** [comment]
Fala galera! 

Eu ativei o GitHub pages aqui e esqueci de fechar essa issue.

Aqui está o link: https://woliveiras.com.br/front-end-career/

Agora vou montar um tema legal pra substituir esse do GitHub simplão. :smile:
