### ISSUE TITLE
Eventos

### ISSUE THREAD

**Issue by DWoonD** [woliveiras/front-end-career#18]
Temos algum lugar para eventos ou podemos criar um igual a lista do pessoal?

**Comment by woliveiras** [comment]
Pra eventos, da pra pegar um desses sites que listam todos mano.

Assim evitamos descentralizar as informações. :)

**Comment by danilovaz** [comment]
Também acho que não tem a necessidade de criar um dentro desse repo. Já existem vários por aí e seria mais prático só linkar:

[Eventos Front BR](https://github.com/frontendbr/eventos)
[Eventos Dev em geral no mundo](https://github.com/danilovaz/eventos)
[Calendário de eventos](https://github.com/saiadecasa/saiadecasa.github.io)
[Lista de Meetups no Brasil](https://github.com/cerebrobr/meetups)

**Comment by woliveiras** [comment]
Show mano, já coloquei no README esses links! o/

**Comment by woliveiras** [comment]
Posso fechar a issue @DWoonD?
