### ISSUE TITLE
Translate the pt-br version to other languages

### ISSUE THREAD

**Issue by woliveiras** [woliveiras/front-end-career#19]
Translate the pt-br version to other languages
- [x] English
- [ ] Spanish

**Comment by Marcelosilva10** [comment]
Vou ver se consigo traduzir alguns conteúdos interessantes do medium para poder colocar nos repositórios o que acha @woliveiras ?

**Comment by woliveiras** [comment]
Acho show de bola cara! 

Temos um projeto rolando no FEMUG-ABC para traduções. [Aqui](https://github.com/femug-abc/femug-abc/tree/master/projects/translations). Chega junto! 😄

**Comment by woliveiras** [comment]
O esquema que precisamos aqui no repo é passar do PT-BR pra inglês.

Bora @Marcelosilva10 ?

**Comment by Marcelosilva10** [comment]
Bora acho que isso pode ajudar aprofundar inglês também.
@woliveiras tem algum open que precisa de um helper tbm?

**Comment by woliveiras** [comment]
Dos meus, acho que só esse que precisa de tradução mano. De resto tem outras coisas ein... 

https://github.com/woliveiras/FFAQ/issues
https://github.com/woliveiras/kibe/issues
https://github.com/woliveiras/wp-workflow/issues
https://github.com/woliveiras/pastel/issues

Chega lá mano. 🙌

**Comment by lnmunhoz** [comment]
Vocês ja começaram? Eu posso ajudar com isso :) 
Se sim sobre pra uma branch por favor.

**Comment by woliveiras** [comment]
Ainda não @lnmunhoz,

Eu pretendo começar sábado que vem a fazer algumas coisas.
Se quiserem podemos criar um plano pra isso. Crio umas issues por sessão, assim fica mais fácil organizar pra traduzir em grupo.
Que tal?

**Comment by Marcelosilva10** [comment]
Da para separar por pessoas o que acham?

**Comment by woliveiras** [comment]
Demorou @Marcelosilva10 

Eu não consegui um tempo pra começar, mas logo logo agilizo isso.

Vou criar as issues e cada um pode ir pegando de acordo com a disponibilidade de tempo. :raised_hands:

**Comment by woliveiras** [comment]
Issues criadas galera!

Falta criar a sessão do [Front End UI Developer](https://github.com/woliveiras/front-end-career/issues/20), então ela não entrou na lista.

Podemos ir fazendo na Branch [translate-en-us](https://github.com/woliveiras/front-end-career/tree/translate-en-us).

Quando alguém pegar alguma issue pra resolver, comenta lá que eu mudo a label pra `work in progress` pra ninguém fazer a mesma coisa.
