### ISSUE TITLE
Tipos de contratação

### ISSUE THREAD

**Issue by woliveiras** [woliveiras/front-end-career#2]
Listar os tipos de contratação e como funcionam:
- CLT
- PJ

**Comment by thebergamo** [comment]
Agora tem o Flex também né?

**Comment by woliveiras** [comment]
E o tal do associado, ainda, @thebergamo.

Se tiver algum link pra falar sobre isso, manda ae pra gente. :smile:

**Comment by thebergamo** [comment]
Tá na mão @woliveiras 

http://www.guj.com.br/t/tipos-de-contratacao-qual-a-diferenca/49184

**Comment by woliveiras** [comment]
Shooow

**Comment by woliveiras** [comment]
Tá lá! :smile:
