### ISSUE TITLE
Translate [O que todo(a) Desenvolvedor(a) de Software precisa saber] session

### ISSUE THREAD

**Issue by woliveiras** [woliveiras/front-end-career#26]
Translate [O que todo(a) Desenvolvedor(a) de Software precisa saber] session in home project.

Related to: [#19](https://github.com/woliveiras/front-end-career/issues/19#issuecomment-233288837)
- [x] es
- [x] en

**Comment by effexts** [comment]
Eu pozzo facer isso / Yo puedo hacer esto.

**Comment by woliveiras** [comment]
Gracias @effexts! :smile:

**Comment by marcoaure** [comment]
Vou contribuir com a tradução para o [EN]

**Comment by woliveiras** [comment]
Valeu @marcoaure

**Comment by woliveiras** [comment]
Done #50!
