### ISSUE TITLE
Translate [Escolhendo um lado] session

### ISSUE THREAD

**Issue by woliveiras** [woliveiras/front-end-career#27]
Translate [Escolhendo um lado] session in home project.

Related to: [#19](https://github.com/woliveiras/front-end-career/issues/19#issuecomment-233288837)
- [x] es
- [x] en

**Comment by effexts** [comment]
Spanish translations is ready. (Home Section)

**Comment by woliveiras** [comment]
Great! Thanks @effexts :raised_hands:

**Comment by rafajaques** [comment]
I can take english. How to get the job done?

**Comment by woliveiras** [comment]
Can take it @rafajaques!

You can pick up other issues too. 

Thanks!

**Comment by marcoaure** [comment]
@woliveiras vou traduzir para o [EN]

**Comment by marcoaure** [comment]
#51

**Comment by woliveiras** [comment]
Merged! :metal:  :metal:  :metal:

**Comment by woliveiras** [comment]
Thanks all!
