### ISSUE TITLE
Translate [Links para estudar sobre Front End] session

### ISSUE THREAD

**Issue by woliveiras** [woliveiras/front-end-career#30]
Translate [Links para estudar sobre Front End] session in home project

Related to: [#19](https://github.com/woliveiras/front-end-career/issues/19#issuecomment-233288837)
- [x] es
- [x] en

**Comment by effexts** [comment]
Spanish translations is ready. (Home Section)

**Comment by woliveiras** [comment]
Great! Thanks @effexts :raised_hands:

**Comment by sirmatheus** [comment]
Olá @woliveiras conclui a tradução dessa sessão, só cometi um erro na hora do commit e fiz outro, esse foi meu primeiro PR :sweat_smile:

**Comment by woliveiras** [comment]
Olá @matheusfurtado94 

Parabéns por tomar coragem e mandar seu primeiro PR!!! :raised_hands: 

Sem problemas. :smile:
