### ISSUE TITLE
Translate [Mantendo-se atualizado] session

### ISSUE THREAD

**Issue by woliveiras** [woliveiras/front-end-career#31]
Translate [Mantendo-se atualizado] session in home project

Related to: [#19](https://github.com/woliveiras/front-end-career/issues/19#issuecomment-233288837)
- [x] es
- [x] en

**Comment by effexts** [comment]
Spanish translations is ready. (Home Section)

**Comment by woliveiras** [comment]
Great! Thanks @effexts :raised_hands:
