### ISSUE TITLE
Translate [Quero trabalhar no exterior] session

### ISSUE THREAD

**Issue by woliveiras** [woliveiras/front-end-career#32]
Translate [Quero trabalhar no exterior] session in home project

Related to: [#19](https://github.com/woliveiras/front-end-career/issues/19#issuecomment-233288837)
- [x] es
- [x] en

**Comment by effexts** [comment]
Spanish translations is ready. (Home Section)

**Comment by woliveiras** [comment]
Great! Thanks @effexts :raised_hands:

**Comment by woliveiras** [comment]
Thanks @effexts and @camilatigre
