### ISSUE TITLE
Translate [Perguntas frequêntes sobre Desenvolvimento Front End] session

### ISSUE THREAD

**Issue by woliveiras** [woliveiras/front-end-career#33]
Translate [Perguntas frequêntes sobre Desenvolvimento Front End] session in home project

Related to: [#19](https://github.com/woliveiras/front-end-career/issues/19#issuecomment-233288837)
- [x] es
- [x] en

**Comment by effexts** [comment]
Spanish translations is ready. (Home Section)

**Comment by woliveiras** [comment]
Great! Thanks @effexts :raised_hands:

**Comment by sirmatheus** [comment]
Olá @woliveiras  fiz a tradução em inglês para essa sessão 😃

**Comment by woliveiras** [comment]
Show @matheusfurtado94 

Valeeeu!
