### ISSUE TITLE
Translate [Developer - Junior] session

### ISSUE THREAD

**Issue by woliveiras** [woliveiras/front-end-career#34]
Translate [Developer - Junior] session on [this link](https://github.com/woliveiras/front-end-career/blob/master/translations/pt-br/sources/developer.md#júnior).

Related to: [#19](https://github.com/woliveiras/front-end-career/issues/19#issuecomment-233288837)
- [x] es
- [x] en

**Comment by effexts** [comment]
Doing this right now. I'm not sure if I can complete the file, but I will close this first part of the issue, to "es". Later I can do it for "en".

**Comment by woliveiras** [comment]
Thanks man!

You're helping a lot!

**Comment by thiamsantos** [comment]
@woliveiras I am translating to English maybe tomorrow I will send the pull request.

**Comment by woliveiras** [comment]
Very cool @thiamsantos 

Thanks!
