### ISSUE TITLE
Translate [Developer - Mid Level (Pleno)] session

### ISSUE THREAD

**Issue by woliveiras** [woliveiras/front-end-career#35]
Translate [Developer - Mid Level (Pleno)] session on [this link](https://github.com/woliveiras/front-end-career/blob/master/translations/pt-br/sources/developer.md#pleno).

Related to: [#19](https://github.com/woliveiras/front-end-career/issues/19#issuecomment-233288837)
- [x] es
- [x] en

**Comment by thiamsantos** [comment]
@woliveiras I am translating to English, maybe tomorrow I will send the pull request.

**Comment by woliveiras** [comment]
:raised_hands: :raised_hands: :raised_hands: 

Thanks @thiamsantos
