### ISSUE TITLE
Translate [Developer - sênior] session

### ISSUE THREAD

**Issue by woliveiras** [woliveiras/front-end-career#36]
Translate [Developer - sênior] session on [this link](https://github.com/woliveiras/front-end-career/blob/master/translations/pt-br/sources/developer.md#sênior).

Related to: [#19](https://github.com/woliveiras/front-end-career/issues/19#issuecomment-233288837)
- [ ] es
- [x] en

**Comment by thiamsantos** [comment]
@woliveiras I am translating to English, maybe tomorrow I will send the pull request.

**Comment by woliveiras** [comment]
Great @thiamsantos!!

Thanks by help!
