### ISSUE TITLE
Translate [Front End Engineer - Junior] session

### ISSUE THREAD

**Issue by woliveiras** [woliveiras/front-end-career#37]
Translate [Front End Engineer - Junior] session on [this link](https://github.com/woliveiras/front-end-career/blob/master/translations/pt-br/sources/engineer.md#front-end-engineer-júnior)

Related to: [#19](https://github.com/woliveiras/front-end-career/issues/19#issuecomment-233288837)
- [x] es
- [x] en

**Comment by danilovaz** [comment]
:es: #65

**Comment by woliveiras** [comment]
:metal: :metal: :metal: :metal: 

Valeu manooo
