### ISSUE TITLE
Translate [Front End Engineer - Pleno] 

### ISSUE THREAD

**Issue by woliveiras** [woliveiras/front-end-career#38]
Translate [Front End Engineer - Pleno] session on [this link](https://github.com/woliveiras/front-end-career/blob/master/translations/pt-br/sources/engineer.md#front-end-engineer-pleno)

Related to: [#19](https://github.com/woliveiras/front-end-career/issues/19#issuecomment-233288837)
- [ ] es
- [x] en

**Comment by daliannyvieira** [comment]
Doing

**Comment by woliveiras** [comment]
Thanks @daliannyvieira!! :heart:
