### ISSUE TITLE
Translate [Front End Engineer - Sênior] session

### ISSUE THREAD

**Issue by woliveiras** [woliveiras/front-end-career#39]
Translate [Front End Engineer - Sênior] session on [this link](https://github.com/woliveiras/front-end-career/blob/master/translations/pt-br/sources/engineer.md#front-end-engineer-sênior)

Related to: [#19](https://github.com/woliveiras/front-end-career/issues/19#issuecomment-233288837)
- [ ] es
- [x] en

**Comment by iamfelipemattos** [comment]
I gonna try translate

**Comment by woliveiras** [comment]
Thanks @IAMFELIPEMATTOS

**Comment by rolisanchez** [comment]
Ainda precisa de ajuda com o espanhol? É minha língua materna então posso ajudar. Também percebi que o readme.md está usando voz formal e informal ao mesmo tempo (Equivalente a usar "o senhor precisa olhar esse material" e "você precisa olhar esse material" ao mesmo tempo em português). Também tem uns outros detalhes que podem ser corrigidos :)

**Comment by woliveiras** [comment]
Opa! 

@rolisanchez, preciso mais de uma revisão geral hoje em dia, por que tem esses errinhos que você comentou, viu.

Se conseguir me ajudar nessa será uma MEGA ajuda! :pray:
