### ISSUE TITLE
Para iniciantes

### ISSUE THREAD

**Issue by jonatasleon** [woliveiras/front-end-career#4]
Esse link pode ser muito útil para quem está começando como front-end
http://willianjusten.com.br/como-se-tornar-um-desenvolvedor-front-end/

**Comment by woliveiras** [comment]
Esse link do Will é muito bom! Valeu @jonatasleon

**Comment by DWoonD** [comment]
https://leandrooriente.com/como-me-tornar-um-desenvolvedor-front-end/

Esse do leandro oriente também é legal

**Comment by woliveiras** [comment]
Boa véi!

Já já vou atualizar com esses links! :D

**Comment by jonathanslima** [comment]
Desse que foram feitos, acho de longe o do Leandro o mais completo. Segue outros links
https://leandrooriente.com/guia-de-estudo-front-end/
http://tableless.com.br/tornar-dev-front-end/

**Comment by grodrigues** [comment]
Os videos deles sempre são bons
https://www.youtube.com/user/rodrigobranas

**Comment by woliveiras** [comment]
Valeu ein galera, coloquei os links como [referencia](https://github.com/woliveiras/front-end-career/blob/master/REFERENCE.md) e vou espalhar eles pra tudo que é lado no repositório! kkkkk
