### ISSUE TITLE
Escolha um lado

### ISSUE THREAD

**Issue by danilovaz** [woliveiras/front-end-career#5]
Esse tema sobre qual a denominação correta quando se trata do cargo de Front-end foi um tema muito bom nessa [issue](https://github.com/frontendbr/forum/issues/32)

Particularmente acho que a proposta da @diessica tem mais coerência com as habilidades e objetivos do Front voltado mais pra design.

Fica minha sugestão aí se achar ser válida, assim quem começa sua carreira já tem um norte mais delineado. Porque o papel do Front-end Designer vai muito além de design, é responsável por toda a interface e suas variáveis (interações e tal). O Front-end Designer dá a falsa impressão que basta conhecer HTML/CSS e Photoshop (e derivados) pra se tornar um.

**Comment by woliveiras** [comment]
Pow, verdade mano. Vou atualizar! 

Valeu.

**Comment by DWoonD** [comment]
Pelo que vejo nas vagas, o front end Designer junior tem que ter photoshop ilustrator ou outro programa de vetor e manipulação, HTML, CSS E JS

Já o enginner é HTML CSS E JS, muito bem js, de preferência algum framework

isso tudo pra junior

**Comment by woliveiras** [comment]
Atualizado! :D

Já já vou colocar mais informações sobre o Engineer e o UI Developer conforme o post da @diessica

**Comment by jonathanslima** [comment]
Escrevi vinte centavos sobre isso aqui: http://jonathanslima.github.io/2016/sobre-front-enders-e-unicornios/

Li o post da Diessica e achei bacana o ponto de vista dela tb. Mas acho que isso não devia ser taxativo. A área ainda é muito nova, dinâmica e relativamente aberta a absorção de conteúdo. É que nem o UX, que ainda tem gente que chama de Arquiteto de informação, e outros de Designer de Interação.

Acredito que sejam só nomes. Aqui em Recife mesmo o pessoal chama de webdesigner ou front end. UI developer é desconhecido por aqui. Acho que isso varia muito de região pra região.

**Comment by woliveiras** [comment]
No caso é bom ter a divisão pra pessoa ter um foco mano.

Tipo, se coloca uma pessoa com perfil mais voltado para o Design para mexer com um monte de JavaScript, Patterns, Build, Continuous Deploy, Continuous Integration, etc, essa pessoa pira. Não faz parte do que ela curte sabe?

Talvez, pelo título: Designer ou UI Developer, não fique claro na vaga de emprego pela nossa localidade, mas a gente tem um direcionamento para o nosso perfil, pra poder focar, pelo menos, sabe?

Se coloca a pessoa pra ficar ninja em UI e ninja em Arquitetura de Software, essa pessoa pira. É coisa pra caramba pra estudar! kkkk

Tem empresas que o Front não mexe com HTML e CSS, por exemplo, só JavaScript e outras que a pessoa quase não escreve JS, só HTML e CSS a lote.

Acaba sendo regional a nomenclatura, como você diz, mas é bom a pessoa saber que existe algo que é bom pra ela e ela não precisa se adequar a uma localidade. Se ela souber que existe lugar que contrata pra fazer o que ela gosta, ela pode se preparar e ir pra lá.

A gente pode dominar o mundo mano! \o/

**Comment by jonathanslima** [comment]
Essa é a parte boa mano, dominar o mundo kkkk e da sua casa ainda mais. Confesso que fiquei maluco com o tanto de coisa pra estudar que cheguei a abandonar a área por um tempo. Meu foco hj é mais no UI Developer, mas quero estudar pra sacar as outras áreas do front tb. Isso dá uma boa discussão .

**Comment by woliveiras** [comment]
Sim mano! kkkk

**Comment by woliveiras** [comment]
Foi atualizado no README. Qualquer coisa podemos reabrir a issue galera. Valeu!
