### ISSUE TITLE
Lista de pessoas para seguir BR (minha opinião)

### ISSUE THREAD

**Issue by DWoonD** [woliveiras/front-end-career#8]
Daniel Filho
Diego Eis
Willian Justen
Eduardo Shiota
Caio Godin
Zeno Rocha
Raphael Fabeni
Rafael Rinaldi
Sergio Lopes
Ze fernandes
Eduardo Matos
Dani Gueratto
Leandro Lima
Bernard de Luna
Jaydson Gomes
Almir Filho
Maujor
Talita Pagani

**Comment by woliveiras** [comment]
Já saca do PR com os dados desses caras mano!

Da uma olhada na [lista](https://github.com/woliveiras/front-end-career/blob/master/great-developers.md).

**Comment by woliveiras** [comment]
@DWoonD, faltam só esses aqui:
- Daniel Filho
- Diego Eis
- Rafael Rinaldi
- Ze fernandes
- Eduardo Matos
- Dani Gueratto
- Leandro Lima
- Bernard de Luna
- Talita Pagani

Você quer colocar eles mano?

[Lista](https://github.com/woliveiras/front-end-career/blob/master/great-developers.md)

**Comment by Marcelosilva10** [comment]
ótimo vou ver!
