### ISSUE TITLE
In English?

### ISSUE THREAD

**Issue by davidpelayo** [woliveiras/front-end-career#9]
I don't have issues with the original language you are writing, but I think it would be more useful to spread the word in more languages, like English or Spanish (I can translate it if you want to Spanish).

What do you think?

**Comment by woliveiras** [comment]
:+1: :+1: :+1: :+1: :+1: :+1:

It's great @davidpelayo! :smile: 

I named the repository in english to translate for english or more languages in future, but we can start already multi language.

I go to prepare a scheme for several languages now, then you can help.

**Comment by woliveiras** [comment]
Look the schema, @davidpelayo, and tell me if is cool. :smile:

**Comment by davidpelayo** [comment]
I think for now it's pretty ok. I also added the spanish version on #10.

**Comment by woliveiras** [comment]
Great @davidpelayo!

Thanks.

**Comment by woliveiras** [comment]
I think we can close the issue, you agree?

**Comment by davidpelayo** [comment]
Sure!
